tools:
    php_cpd:
        enabled: true
        filter:               
            paths: ["src/*"]
    php_mess_detector:
        enabled: true
        filter:               
            paths: ["src/*"]
    php_cs_fixer: 
        filter:                 
            paths: ["src/*"]
        enabled: true        
        config:               
            level: all
    php_analyzer:
        enabled: true        
        filter:                 
            paths: ["src/*"]
    php_code_sniffer:     
        filter:                 
            paths: ["src/*"]
        enabled: true
        config:               
            standard: PSR2 
    sensiolabs_security_checker: true
