before_commands:
    - "composer install --prefer-dist"

tools:
    php_cpd:
        enabled: false
    php_mess_detector:
        enabled: true
        filter:
            paths: ["src/*"]
            excluded_paths: ["src/Camspiers/StatisticalClassifier/StatisticalClassifierServiceContainer.php"]
    php_cs_fixer:
        enabled: true
        filter:
            paths: ["src/*"]
            excluded_paths: ["src/Camspiers/StatisticalClassifier/StatisticalClassifierServiceContainer.php"]
        config:
            level: all
    php_analyzer:
        enabled: true
        filter:
            paths: ["src/*"]
            excluded_paths: ["src/Camspiers/StatisticalClassifier/StatisticalClassifierServiceContainer.php"]
    php_code_sniffer:
        enabled: true
        filter:
            paths: ["src/*"]
            excluded_paths: ["src/Camspiers/StatisticalClassifier/StatisticalClassifierServiceContainer.php"]
        config:
            standard: PSR2
    php_code_coverage:
        config_path:          ~
        test_command:         phpunit
        only_changesets: false
        enabled: true
        filter:
            paths: ["src/*"]
