tools:
    php_cpd:
        enabled: false
        filter:
            paths: ["src/"]
    php_mess_detector:
        enabled: true
        filter:
            paths: ["src/"]
        command: vendor/bin/phpmd
    php_cs_fixer:
        enabled: true
        filter:
            paths: ["src/"]
        config:
            level: all
    php_analyzer:
        enabled: false
        filter:
            paths: ["src/"]
    php_code_sniffer:
        enabled: true
        filter:
            paths: ["src/"]
        config:
            standard: PSR2
        command: vendor/bin/phpcs
    php_code_coverage:
        enabled: true
        test_command: vendor/bin/phpunit
