tools:
    php_cpd:
        enabled: false
        filter:
            paths: ["src/*"]
    php_mess_detector:
        enabled: true
        filter:
            paths: ["src/*"]
    php_cs_fixer:
        enabled: true
        filter:
            paths: ["src/*"]
        config:
            level: all
    php_analyzer:
        enabled: false
        filter:
            paths: ["src/*"]
    php_code_sniffer:
        enabled: true
        filter:
            paths: ["src/*"]
        config:
            standard: PSR2
    php_code_coverage: true
