language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - hhvm
  
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libsvm-dev
  - command -v pecl && pecl install svm-beta

before_script:
  - composer self-update
  - composer install --dev

script:
  - phpunit --coverage-clover=coverage.clover
  
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php -r "if (version_compare(PHP_VERSION, '5.4.0') >= 0) { passthru('php ocular.phar code-coverage:upload --format=php-clover coverage.clover'); }"
