language: php

php:
  - 5.3
  - 5.4
  
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libsvm-dev
  - pecl install svm-beta

before_script:
  - composer self-update
  - composer install --dev

script:
    phpunit --coverage-clover=coverage.clover
    wget https://scrutinizer-ci.com/ocular.phar
    php ocular.phar code-coverage:upload --format=php-clover coverage.clover
