parameters:

services:
    tokenizer.word:
        class: Camspiers\StatisticalClassifier\Tokenizers\Word
    normalizer.lowercase:
        class: Camspiers\StatisticalClassifier\Normalizers\Lowercase
    normalizer.porter:
        class: Camspiers\StatisticalClassifier\Normalizers\Porter

    converter.converter:
        class: Camspiers\StatisticalClassifier\DataSource\Converter
        arguments:
            - @converter.from
            - @converter.to
    converter.from:
        synthetic: true
    converter.to:
        synthetic: true

    classifier.naive_bayes:
        class: Camspiers\StatisticalClassifier\Classifiers\NaiveBayes
        arguments:
            - @classifier.data_source
            - @tokenizer.word
            - @normalizer.lowercase
        calls:
            - [ addHeuristic, [ @heuristic.tf_threaded ] ]
            - [ addHeuristic, [ @heuristic.idf ] ]
            - [ addHeuristic, [ @heuristic.dl ] ]

    classifier.data_source:
        synthetic: true

    heuristic.tf:
        class: Camspiers\StatisticalClassifier\Heuristics\TF

    heuristic.tf_threaded:
        class: Camspiers\StatisticalClassifier\Heuristics\TFThreaded

    heuristic.idf:
        class: Camspiers\StatisticalClassifier\Heuristics\IDF

    heuristic.dl:
        class: Camspiers\StatisticalClassifier\Heuristics\DL
