imports:
    - { resource: stopwords.yml }

parameters:
    cache.backend.options:
        dir: ./indexes/
        file_extension: .idx

services:
    # Tokenizers
    tokenizer.word:
        class: Camspiers\StatisticalClassifier\Tokenizer\Word

    # Normalizers
    normalizer.lowercase:
        class: Camspiers\StatisticalClassifier\Normalizer\Lowercase
    normalizer.porter:
        class: Camspiers\StatisticalClassifier\Normalizer\Porter
    normalizer.stopword:
        class: Camspiers\StatisticalClassifier\Normalizer\Stopword
        arguments:
            - %stopwords%
    normalizer.stopword_lowercase:
        class: Camspiers\StatisticalClassifier\Normalizer\Grouped
        arguments:
            - [ @normalizer.stopword, @normalizer.lowercase ]
    normalizer.stopword_lowercase_porter:
        class: Camspiers\StatisticalClassifier\Normalizer\Grouped
        arguments:
            - [ @normalizer.stopword, @normalizer.lowercase, @normalizer.porter  ]

    # Converter
    converter.converter:
        class: Camspiers\StatisticalClassifier\DataSource\Converter
        arguments:
            - @converter.from
            - @converter.to

    converter.from:
        synthetic: true
    converter.to:
        synthetic: true

    # Classifiers
    classifier.naive_bayes:
        class: Camspiers\StatisticalClassifier\Classifier\NaiveBayes
        arguments:
            - @index.index
            - @tokenizer.word
            - @normalizer.stopword_lowercase

    # Indexes
    index.index:
        synthetic: true

    # Transforms
    transform.tf:
        class: Camspiers\StatisticalClassifier\Transform\TF

    transform.tf_threaded:
        class: Camspiers\StatisticalClassifier\Transform\TFThreaded

    transform.idf:
        class: Camspiers\StatisticalClassifier\Transform\IDF

    transform.dl:
        class: Camspiers\StatisticalClassifier\Transform\DL

    # Caches
    cache:
        class: CacheCache\Cache
        arguments:
            - @cache.backend

    cache.backend:
        class: CacheCache\Backends\File
        arguments:
            - %cache.backend.options%

    # Console
    console.application:
        class: Camspiers\StatisticalClassifier\Console\Application

    console.command.index.create:
        class: Camspiers\StatisticalClassifier\Console\Command\Index\CreateCommand
        tags:
            - { name: console.cacheable_command }

    console.command.index.remove:
        class: Camspiers\StatisticalClassifier\Console\Command\Index\RemoveCommand
        tags:
            - { name: console.cacheable_command }

    console.command.index.prepare:
        class: Camspiers\StatisticalClassifier\Console\Command\Index\PrepareCommand
        tags:
            - { name: console.cacheable_command }

    console.command.train.document:
        class: Camspiers\StatisticalClassifier\Console\Command\Train\DocumentCommand
        tags:
            - { name: console.cacheable_command }

    console.command.train.director:
        class: Camspiers\StatisticalClassifier\Console\Command\Train\DirectoryCommand
        tags:
            - { name: console.cacheable_command }

    console.command.classify:
        class: Camspiers\StatisticalClassifier\Console\Command\ClassifyCommand
        tags:
            - { name: console.cacheable_command }

    logger:
        class: Monolog\Logger
        arguments:
            - classifier
        calls:
            - [ pushHandler, [ @logger.stream ] ]

    logger.stream:
        class: Monolog\Handler\StreamHandler
        arguments:
            - logs/classifier.log
            - 100
